# Generated by Django 5.2.3 on 2025-07-03 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requests.helprequest'),
        ),
    ]
