# Generated by Django 5.2.3 on 2025-07-03 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_alter_donation_case'),
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='case',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='requests.helprequest'),
            preserve_default=False,
        ),
    ]
