# Generated by Django 5.2.3 on 2025-07-02 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('medical', 'Medical'), ('school_fees', 'School Fees'), ('rent', 'Rent'), ('disaster_relief', 'Disaster Relief')], max_length=50)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('critical', 'Critical')], max_length=50)),
                ('story', models.TextField()),
                ('media', models.FileField(blank=True, null=True, upload_to='help_requests/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
